### ISSUE TITLE
Could not find the alias @hostmaster

### ISSUE THREAD

**Issue by universam1** [daften/cookbook-aegir3#2]
Thanks for the great work!

Unfortunately, I'm unable to run test kitchen, the installation fails with this error (debug enabled):

```
+ echo Enabling hosting-queued daemon
Enabling hosting-queued daemon
+ su -s /bin/sh aegir -c drush @hostmaster pm-enable -y hosting_queued
Could not find the alias @hostmaster                                 [error]
dpkg: error processing package aegir3-hostmaster (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of aegir3:
 aegir3 depends on aegir3-hostmaster (>= 3.6+354.1aaee66); however:
  Package aegir3-hostmaster is not configured yet.

dpkg: error processing package aegir3 (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
Errors were encountered while processing:
 aegir3-hostmaster
 aegir3
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Tried on 

- Ubuntu 14.4
- Ubuntu 16
- Debian 7

Any idea?

**Comment by daften** [comment]
This is because mysql was installed but isn't secure. I'm gonna adapt the kitchen configuration file and test it out. Thanks for the report :)

**Comment by daften** [comment]
Had some trouble with some boxes because of this bug, but now the kitchen runs should work again properly. Had to disable ubuntu12.04 testing, since it's PHP 5.3 on there and that's not supported anymore in the latest drush version, which is installed by aegir3. I think that won't be a problem, there's two newer LTS releases now :).

BTW: now there's no decent real tests at all. If you wanna help write those, please do!
